/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace VantageRegistry {
  export type PatronConfigStruct = {
    creatorShare: BigNumberish;
    investorShare: BigNumberish;
    treasuryShare: BigNumberish;
    creatorAddr: AddressLike;
    investorAddr: AddressLike;
    treasuryAddr: AddressLike;
  };

  export type PatronConfigStructOutput = [
    creatorShare: bigint,
    investorShare: bigint,
    treasuryShare: bigint,
    creatorAddr: string,
    investorAddr: string,
    treasuryAddr: string
  ] & {
    creatorShare: bigint;
    investorShare: bigint;
    treasuryShare: bigint;
    creatorAddr: string;
    investorAddr: string;
    treasuryAddr: string;
  };

  export type KernelConfigStruct = {
    approvalThreshold: BigNumberish;
    gtmBudget: BigNumberish;
    minPatronPulse: BigNumberish;
  };

  export type KernelConfigStructOutput = [
    approvalThreshold: bigint,
    gtmBudget: bigint,
    minPatronPulse: bigint
  ] & { approvalThreshold: bigint; gtmBudget: bigint; minPatronPulse: bigint };

  export type PulseConfigStruct = {
    tokenAddr: AddressLike;
    totalSupply: BigNumberish;
    priceUsdCents: BigNumberish;
  };

  export type PulseConfigStructOutput = [
    tokenAddr: string,
    totalSupply: bigint,
    priceUsdCents: bigint
  ] & { tokenAddr: string; totalSupply: bigint; priceUsdCents: bigint };

  export type CorpusStruct = {
    id: BigNumberish;
    name: string;
    category: string;
    creator: AddressLike;
    patron: VantageRegistry.PatronConfigStruct;
    kernel: VantageRegistry.KernelConfigStruct;
    pulse: VantageRegistry.PulseConfigStruct;
    createdAt: BigNumberish;
    active: boolean;
  };

  export type CorpusStructOutput = [
    id: bigint,
    name: string,
    category: string,
    creator: string,
    patron: VantageRegistry.PatronConfigStructOutput,
    kernel: VantageRegistry.KernelConfigStructOutput,
    pulse: VantageRegistry.PulseConfigStructOutput,
    createdAt: bigint,
    active: boolean
  ] & {
    id: bigint;
    name: string;
    category: string;
    creator: string;
    patron: VantageRegistry.PatronConfigStructOutput;
    kernel: VantageRegistry.KernelConfigStructOutput;
    pulse: VantageRegistry.PulseConfigStructOutput;
    createdAt: bigint;
    active: boolean;
  };
}

export interface VantageRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "LAUNCHPAD_FEE_BPS"
      | "createCorpus"
      | "creatorOf"
      | "deactivateCorpus"
      | "getCorpus"
      | "isActive"
      | "nextCorpusId"
      | "updateKernel"
      | "updatePatron"
      | "updatePulse"
      | "vantageProtocolWallet"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CorpusCreated"
      | "CorpusDeactivated"
      | "KernelUpdated"
      | "PatronUpdated"
      | "PulseTokenCreated"
      | "PulseUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "LAUNCHPAD_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createCorpus",
    values: [
      string,
      string,
      VantageRegistry.PatronConfigStruct,
      VantageRegistry.KernelConfigStruct,
      VantageRegistry.PulseConfigStruct,
      string,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "creatorOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateCorpus",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCorpus",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isActive",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextCorpusId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateKernel",
    values: [BigNumberish, VantageRegistry.KernelConfigStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePatron",
    values: [BigNumberish, VantageRegistry.PatronConfigStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePulse",
    values: [BigNumberish, VantageRegistry.PulseConfigStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "vantageProtocolWallet",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "LAUNCHPAD_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createCorpus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "creatorOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deactivateCorpus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getCorpus", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isActive", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextCorpusId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateKernel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePatron",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePulse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vantageProtocolWallet",
    data: BytesLike
  ): Result;
}

export namespace CorpusCreatedEvent {
  export type InputTuple = [
    corpusId: BigNumberish,
    creator: AddressLike,
    name: string
  ];
  export type OutputTuple = [corpusId: bigint, creator: string, name: string];
  export interface OutputObject {
    corpusId: bigint;
    creator: string;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CorpusDeactivatedEvent {
  export type InputTuple = [corpusId: BigNumberish];
  export type OutputTuple = [corpusId: bigint];
  export interface OutputObject {
    corpusId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace KernelUpdatedEvent {
  export type InputTuple = [corpusId: BigNumberish];
  export type OutputTuple = [corpusId: bigint];
  export interface OutputObject {
    corpusId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PatronUpdatedEvent {
  export type InputTuple = [corpusId: BigNumberish];
  export type OutputTuple = [corpusId: bigint];
  export interface OutputObject {
    corpusId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PulseTokenCreatedEvent {
  export type InputTuple = [
    corpusId: BigNumberish,
    tokenAddress: AddressLike,
    totalSupply: BigNumberish,
    protocolFee: BigNumberish
  ];
  export type OutputTuple = [
    corpusId: bigint,
    tokenAddress: string,
    totalSupply: bigint,
    protocolFee: bigint
  ];
  export interface OutputObject {
    corpusId: bigint;
    tokenAddress: string;
    totalSupply: bigint;
    protocolFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PulseUpdatedEvent {
  export type InputTuple = [corpusId: BigNumberish];
  export type OutputTuple = [corpusId: bigint];
  export interface OutputObject {
    corpusId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VantageRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): VantageRegistry;
  waitForDeployment(): Promise<this>;

  interface: VantageRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  LAUNCHPAD_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  createCorpus: TypedContractMethod<
    [
      name: string,
      category: string,
      patron: VantageRegistry.PatronConfigStruct,
      kernel: VantageRegistry.KernelConfigStruct,
      pulse: VantageRegistry.PulseConfigStruct,
      tokenName: string,
      tokenSymbol: string
    ],
    [bigint],
    "nonpayable"
  >;

  creatorOf: TypedContractMethod<[corpusId: BigNumberish], [string], "view">;

  deactivateCorpus: TypedContractMethod<
    [corpusId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getCorpus: TypedContractMethod<
    [corpusId: BigNumberish],
    [VantageRegistry.CorpusStructOutput],
    "view"
  >;

  isActive: TypedContractMethod<[corpusId: BigNumberish], [boolean], "view">;

  nextCorpusId: TypedContractMethod<[], [bigint], "view">;

  updateKernel: TypedContractMethod<
    [corpusId: BigNumberish, kernel: VantageRegistry.KernelConfigStruct],
    [void],
    "nonpayable"
  >;

  updatePatron: TypedContractMethod<
    [corpusId: BigNumberish, patron: VantageRegistry.PatronConfigStruct],
    [void],
    "nonpayable"
  >;

  updatePulse: TypedContractMethod<
    [corpusId: BigNumberish, pulse: VantageRegistry.PulseConfigStruct],
    [void],
    "nonpayable"
  >;

  vantageProtocolWallet: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "LAUNCHPAD_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createCorpus"
  ): TypedContractMethod<
    [
      name: string,
      category: string,
      patron: VantageRegistry.PatronConfigStruct,
      kernel: VantageRegistry.KernelConfigStruct,
      pulse: VantageRegistry.PulseConfigStruct,
      tokenName: string,
      tokenSymbol: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "creatorOf"
  ): TypedContractMethod<[corpusId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "deactivateCorpus"
  ): TypedContractMethod<[corpusId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getCorpus"
  ): TypedContractMethod<
    [corpusId: BigNumberish],
    [VantageRegistry.CorpusStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isActive"
  ): TypedContractMethod<[corpusId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "nextCorpusId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "updateKernel"
  ): TypedContractMethod<
    [corpusId: BigNumberish, kernel: VantageRegistry.KernelConfigStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updatePatron"
  ): TypedContractMethod<
    [corpusId: BigNumberish, patron: VantageRegistry.PatronConfigStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updatePulse"
  ): TypedContractMethod<
    [corpusId: BigNumberish, pulse: VantageRegistry.PulseConfigStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "vantageProtocolWallet"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "CorpusCreated"
  ): TypedContractEvent<
    CorpusCreatedEvent.InputTuple,
    CorpusCreatedEvent.OutputTuple,
    CorpusCreatedEvent.OutputObject
  >;
  getEvent(
    key: "CorpusDeactivated"
  ): TypedContractEvent<
    CorpusDeactivatedEvent.InputTuple,
    CorpusDeactivatedEvent.OutputTuple,
    CorpusDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "KernelUpdated"
  ): TypedContractEvent<
    KernelUpdatedEvent.InputTuple,
    KernelUpdatedEvent.OutputTuple,
    KernelUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "PatronUpdated"
  ): TypedContractEvent<
    PatronUpdatedEvent.InputTuple,
    PatronUpdatedEvent.OutputTuple,
    PatronUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "PulseTokenCreated"
  ): TypedContractEvent<
    PulseTokenCreatedEvent.InputTuple,
    PulseTokenCreatedEvent.OutputTuple,
    PulseTokenCreatedEvent.OutputObject
  >;
  getEvent(
    key: "PulseUpdated"
  ): TypedContractEvent<
    PulseUpdatedEvent.InputTuple,
    PulseUpdatedEvent.OutputTuple,
    PulseUpdatedEvent.OutputObject
  >;

  filters: {
    "CorpusCreated(uint256,address,string)": TypedContractEvent<
      CorpusCreatedEvent.InputTuple,
      CorpusCreatedEvent.OutputTuple,
      CorpusCreatedEvent.OutputObject
    >;
    CorpusCreated: TypedContractEvent<
      CorpusCreatedEvent.InputTuple,
      CorpusCreatedEvent.OutputTuple,
      CorpusCreatedEvent.OutputObject
    >;

    "CorpusDeactivated(uint256)": TypedContractEvent<
      CorpusDeactivatedEvent.InputTuple,
      CorpusDeactivatedEvent.OutputTuple,
      CorpusDeactivatedEvent.OutputObject
    >;
    CorpusDeactivated: TypedContractEvent<
      CorpusDeactivatedEvent.InputTuple,
      CorpusDeactivatedEvent.OutputTuple,
      CorpusDeactivatedEvent.OutputObject
    >;

    "KernelUpdated(uint256)": TypedContractEvent<
      KernelUpdatedEvent.InputTuple,
      KernelUpdatedEvent.OutputTuple,
      KernelUpdatedEvent.OutputObject
    >;
    KernelUpdated: TypedContractEvent<
      KernelUpdatedEvent.InputTuple,
      KernelUpdatedEvent.OutputTuple,
      KernelUpdatedEvent.OutputObject
    >;

    "PatronUpdated(uint256)": TypedContractEvent<
      PatronUpdatedEvent.InputTuple,
      PatronUpdatedEvent.OutputTuple,
      PatronUpdatedEvent.OutputObject
    >;
    PatronUpdated: TypedContractEvent<
      PatronUpdatedEvent.InputTuple,
      PatronUpdatedEvent.OutputTuple,
      PatronUpdatedEvent.OutputObject
    >;

    "PulseTokenCreated(uint256,address,uint256,uint256)": TypedContractEvent<
      PulseTokenCreatedEvent.InputTuple,
      PulseTokenCreatedEvent.OutputTuple,
      PulseTokenCreatedEvent.OutputObject
    >;
    PulseTokenCreated: TypedContractEvent<
      PulseTokenCreatedEvent.InputTuple,
      PulseTokenCreatedEvent.OutputTuple,
      PulseTokenCreatedEvent.OutputObject
    >;

    "PulseUpdated(uint256)": TypedContractEvent<
      PulseUpdatedEvent.InputTuple,
      PulseUpdatedEvent.OutputTuple,
      PulseUpdatedEvent.OutputObject
    >;
    PulseUpdated: TypedContractEvent<
      PulseUpdatedEvent.InputTuple,
      PulseUpdatedEvent.OutputTuple,
      PulseUpdatedEvent.OutputObject
    >;
  };
}
